---
Standards:
  -
    Title: New Teammate Checklist
    Description: Systems and items to get done in your 1st week at Ada.
    UID: 8547b2c0-41c1-4615-abd2-f1499ae51229
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 27fecb60-d90f-496a-bcc7-f9349719a7a1
        Path: /setup-checklist/accounts.md
  -
    Title: Educational Practices
    Description: Regular practices as part of the ed-team
    UID: c120bdd0-2303-42c2-8578-c9ee4ddc5aa2
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 71d8142849851c1999d31842cddb2aa4
        Path: /educational-practices/assignments.md
      -
        Type: Lesson
        UID: eed8aee3-203b-4e77-919f-2b0e8e812920
        Path: /educational-practices/team-meetings.md
      -
        Type: Lesson
        UID: 662c942c-a246-428d-9914-c213f880d33a
        Path: /educational-practices/student-meetings.md
      -
        Type: Lesson
        UID: 32b08df4-8a82-4b72-aaa8-bf6414990f82
        Path: /educational-practices/company-presentations.md
      -
        Type: Lesson
        UID: 835259f0-2fee-49e7-83da-3900c01d74ff
        Path: /educational-practices/capstone.md