---
Standards:
  -
    Title: New Teammate Checklist
    Description: Systems and items to get done in your 1st week at Ada.
    UID: 8547b2c0-41c1-4615-abd2-f1499ae51229
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 27fecb60-d90f-496a-bcc7-f9349719a7a1
        Path: /setup-checklist/accounts.md
      -
        Type: Lesson
        UID: dbe01a3a-a16b-4c0b-b611-1b8655c89739
        Path: /setup-checklist/calendars.md
      -
        Type: Lesson
        UID: 6ffb0836-ef87-467c-9e84-7d2fed99fa5f
        Path: /setup-checklist/gdrive.md
  -
    Title: Educational Practices
    Description: Regular practices as part of the ed-team
    UID: c120bdd0-2303-42c2-8578-c9ee4ddc5aa2
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 71d8142849851c1999d31842cddb2aa4
        Path: /educational-practices/assignments.md
      -
        Type: Lesson
        UID: eed8aee3-203b-4e77-919f-2b0e8e812920
        Path: /educational-practices/team-meetings.md
      -
        Type: Lesson
        UID: 662c942c-a246-428d-9914-c213f880d33a
        Path: /educational-practices/student-meetings.md
      -
        Type: Lesson
        UID: 32b08df4-8a82-4b72-aaa8-bf6414990f82
        Path: /educational-practices/company-presentations.md
      -
        Type: Lesson
        UID: 835259f0-2fee-49e7-83da-3900c01d74ff
        Path: /educational-practices/capstone.md
  -
    Title: Online Tools
    Description: Tools the educational team uses
    UID: 4ea42d44-b2f9-4841-9c83-ec360f40e24e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 49a825fd-a20f-407c-bc47-b6244d005af4
        Path: /online-tools/online-tools-list.md
      -
        Type: Lesson
        UID: c02557c2-3c6a-436d-8d60-f6c389c79c5f
        Path: /online-tools/documents.md
      -
        Type: Lesson
        UID: 2741d749-440b-4c6f-91b8-f863dac083f9
        Path: /online-tools/github.md
      -
        Type: Lesson
        UID: 20762e80-52bf-4df7-a171-6cbc11a9623d
        Path: /online-tools/hr-tools.md
      -
        Type: Lesson
        UID: 9ed14e17-681d-456b-a1d5-74e08de489e2
        Path: /online-tools/slack.md
      -
        Type: Lesson
        UID: 2e770133-af99-4c6f-9755-5d9de261173d
        Path: /online-tools/video-tools.md
      -
        Type: Lesson
        UID: 7d0a506e-4860-42dd-85b6-8dd39f9f42dc
        Path: /online-tools/zoom.md        